server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.49:3306/tensquare_base?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
  rabbitmq:
    host: 192.168.2.49
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.49:6868/eureka
  instance:
    prefer-ip-address: true
